# Generated by Django 4.2.19 on 2025-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('logDetails', models.TextField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
