# Generated by Django 4.2.19 on 2025-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_add', models.CharField(max_length=50, unique=True)),
                ('to_add', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('m_status', models.CharField(choices=[('S', 'Seen'), ('US', 'Unseen'), ('U', 'Unset')], default='U', max_length=2)),
            ],
        ),
    ]
