# Generated by Django 4.2.19 on 2025-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_add',
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_add',
            field=models.CharField(max_length=50),
        ),
    ]
