# Generated by Django 4.2.19 on 2025-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_message_from_add_alter_message_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
