# Generated by Django 4.2.19 on 2025-02-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycoin',
            name='available',
            field=models.FloatField(default=True),
        ),
    ]
