# Generated by Django 4.2.19 on 2025-03-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_mycoin_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycoin',
            name='owner',
        ),
        migrations.AddField(
            model_name='mycoin',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mycoin',
            name='available',
            field=models.FloatField(default=0),
        ),
    ]
