# Generated by Django 4.2.19 on 2025-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_mycoin_owner_mycoin_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycoin',
            name='available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
