# Generated by Django 4.2.19 on 2025-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell'), ('W', 'Withdraw'), ('D', 'Deposit'), ('T', 'Transfer'), ('U', 'Unset')], default='U', max_length=1)),
                ('from_add', models.CharField(max_length=50, unique=True)),
                ('to_add', models.CharField(max_length=50, unique=True)),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(choices=[('C', 'Complete'), ('UC', 'Uncompleted'), ('F', 'Failed'), ('U', 'Unset')], default='U', max_length=2)),
            ],
        ),
    ]
