# Generated by Django 4.2.19 on 2025-02-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='memecoin_balance',
            field=models.FloatField(default=0),
        ),
    ]
