# Generated by Django 4.2.19 on 2025-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_memecoin_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='memecoin_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
